apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: verseminer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krishnarajt/verseminer
    targetRevision: main
    path: k8s/overlays/linux
  destination:
    server: https://kubernetes.default.svc
    namespace: verseminer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
