apiVersion: apps/v1
kind: Deployment
metadata:
  name: verseminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verseminer
  template:
    metadata:
      labels:
        app: verseminer
    spec:
      containers:
        - name: app
          image: ghcr.io/krishnarajt/verseminer:git-f67c1a3b1376ac3a94050820be2c0b45212aa89c
          imagePullPolicy: IfNotPresent
          command: ["python", "main.py"]

          envFrom:
            - secretRef:
                name: verseminer-env

          volumeMounts:
            - name: app-config
              mountPath: /app/config.yml
              subPath: config.yml
            
            - name: music
              mountPath: /music
            
            - name: db-data
              mountPath: /app/db_data

      volumes:
        - name: app-config
          configMap:
            name: app-config

        - name: music
          hostPath:
            path: /music/albums
            type: Directory
        
        - name: db-data
          persistentVolumeClaim:
            claimName: verseminer-db-pvc