apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: verseminer-env
  namespace: verseminer
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: verseminer-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/verseminer/verseminer/env
